name: Test pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node
      

      - name: Install packages
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci


  docker-build:
    name: Check docker image builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image but dont deploy it
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: test-build
